--
projects: [c-pac, bids-derivatives, c-pac-on-habanero]
author: [Jon Clucas]
date: 2020-07-16
---

- [ ] :construction: C-PAC v1.7.0
   - [x] C-PAC reg-test-1
- [x] BIDS derivatives meeting
- [ ] C-PAC on Habanero

### to do

- [ ] C-PAC {% octicon issue-opened height:12 class:"right left" aria-label:issue %} \#1260
- [ ] C-PAC longitudinal testing
- [ ] C-PAC Python package v0.2.5
- [ ] simplify automated testing (C-PAC)
- [ ] spec Docker image for testing
- [ ] C-PAC ANTS priors testing
- [ ]
   ```Python
   requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/v1.35/containers/f613e7a80272cc015bc1e92a8c16a4c0e73bc3df98988c79a8a3c0df4f7be207/start
 docker.errors.APIError: 500 Server Error: Internal Server Error ("OCI runtime create failed: container_linux.go:348: starting container process caused 
 ```
   on Ned
- [ ] KnowB4 (:calendar: due September 30)

<!--more--> 

### C-PAC regrest-1
```Python
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/shutil.py", line 566, in move
    os.rename(src, real_dst)
FileNotFoundError: [Errno 2] No such file or directory: '/media/ebs/runs/2020-07-15_nightly_regtest-1/working/resting_preproc_sub-0025429_ses-2/anat_mni_ants_register_0/calc_ants_warp/_0x59f703005280b20d3f00133542a46f74_unfinished.json' -> '/media/ebs/runs/2020-07-15_nightly_regtest-1/working/resting_preproc_sub-0025429_ses-2/anat_mni_ants_register_0/calc_ants_warp/_0x59f703005280b20d3f00133542a46f74.json'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 69, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 480, in run
    hashfile_unfinished.replace('_unfinished', ''))
  File "/usr/local/miniconda/lib/python3.7/shutil.py", line 580, in move
    copy_function(src, real_dst)
  File "/usr/local/miniconda/lib/python3.7/shutil.py", line 266, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/local/miniconda/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/media/ebs/runs/2020-07-15_nightly_regtest-1/working/resting_preproc_sub-0025429_ses-2/anat_mni_ants_register_0/calc_ants_warp/_0x59f703005280b20d3f00133542a46f74_unfinished.json'
```

### BIDS derivatives