---
projects: [c-pac-testing]
author: [Jon Clucas]
date: 2020-06-27
end_date: 2020-06-28
---

- [x] Deploy `jonclucas/c-pac_testing_environment:wip` to Docker Hub
- [x] Update [branch `Habanero/1306/spike-censor-not-found`](https://github.com/shnizzedy/C-PAC/tree/Habanero/1306/spike-censor-not-found) to use `jonclucas/c-pac_testing_environment:wip` as base image for CircleCI
- [x] Merge branch `fix/CBIC-test-paths` into `Habanero/1306/spike-censor-not-found`
- [x] Update [branch `Habanero/1306/spike-censor-not-found`](https://github.com/shnizzedy/C-PAC/tree/Habanero/1306/spike-censor-not-found) to run all 20 subjects in [`data-test_4-projects_5-subjects.yml`](https://github.com/shnizzedy/C-PAC/blob/Habanero/1306/spike-censor-not-found/CPAC/resources/configs/test_configs/data-test_4-projects_5-subjects.yml)
- [x] Add Docker CLI to testing Docker image
- [x] Kick off test of all 20 test subjects for Habanero pipeline config.

<!--more-->

<div class="keep-together" markdown="1">
Things that didn't work for testing:
- [![CircleCI failed](https://app.circleci.com/pipelines/favicons/failed-favicon-16x16.png)](https://app.circleci.com/pipelines/github/shnizzedy/C-PAC/86/workflows/3418e434-63f9-4c84-b6d2-b73fe7fc642c/jobs/404) Using local Docker registry with `- setup_remote_docker`:
   ```BASH
   Habanero_1306_spike-censor-not-found: digest: sha256:ee6d89240ab7902a5f0a844b14b7db4d0b473fcc3a78da6336b4ca6ecacd9cbd size: 10410
   ```
   ```Python
   Traceback (most recent call last):
  File "/opt/singularity-2.5.2/libexec/singularity/python/import.py", line 109, in <module>
    main()
  File "/opt/singularity-2.5.2/libexec/singularity/python/import.py", line 86, in main
    layerfile=LAYERFILE)
  File "/opt/singularity-2.5.2/libexec/singularity/python/docker/main.py", line 85, in IMPORT
    client = DockerApiConnection(image=image, auth=auth)
  File "/opt/singularity-2.5.2/libexec/singularity/python/docker/api.py", line 92, in __init__
    self.load_image(kwargs['image'])
  File "/opt/singularity-2.5.2/libexec/singularity/python/docker/api.py", line 146, in load_image
    self.update_token()
  File "/opt/singularity-2.5.2/libexec/singularity/python/docker/api.py", line 191, in update_token
    response = self.get_tags(return_response=True)
  File "/opt/singularity-2.5.2/libexec/singularity/python/docker/api.py", line 314, in get_tags
    return_response=return_response)
  File "/opt/singularity-2.5.2/libexec/singularity/python/base.py", line 291, in get
    updating_token=updating_token)
  File "/opt/singularity-2.5.2/libexec/singularity/python/base.py", line 310, in submit_request
    response = safe_urlopen(request)
  File "/opt/singularity-2.5.2/libexec/singularity/python/base.py", line 152, in safe_urlopen
    return opener.open(url, data=data)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1235, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1205, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 99] Cannot assign requested address>
   ```
- [![CircleCI failed](https://app.circleci.com/pipelines/favicons/failed-favicon-16x16.png)](https://app.circleci.com/pipelines/github/shnizzedy/C-PAC/86/workflows/3418e434-63f9-4c84-b6d2-b73fe7fc642c/jobs/405) Using Docker Hub with `SINGULARITY_NOHTTPS=1`
   ```BASH
   denied: requested access to the resource is denied
   ```
- [![CircleCI failed](https://app.circleci.com/pipelines/favicons/failed-favicon-16x16.png)](https://app.circleci.com/pipelines/github/shnizzedy/C-PAC/86/workflows/3418e434-63f9-4c84-b6d2-b73fe7fc642c/jobs/406) Pushing to Docker Hub without logging in first:
   ```BASH
   The push refers to a repository
   ```
   (Fix by logging in
   ```BASH
   docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
   ```
   )
- [![CircleCI failed](https://app.circleci.com/pipelines/favicons/failed-favicon-16x16.png)](https://app.circleci.com/pipelines/github/shnizzedy/C-PAC/86/workflows/3418e434-63f9-4c84-b6d2-b73fe7fc642c/jobs/407) The home directory of this image was `/root` rather than `/home/circleci`, so
   ```BASH
   The specified paths did not match any files in /home/circleci
   ```
   To fix, set
   ```Dockerfile
   RUN mkdir -p /home/circleci/project
   WORKDIR /home/circleci/project
   ```
   in Dockerfile and 
   ```YAML
   working_directory: /home/circleci/project
   ```
   in Circle config.
   - That also didn't work:
      ```BASH
      Directory (/home/circleci/project) you are trying to checkout to is not empty and not a git repository
      ```
      Tried again with just the YAML changes, not the Dockerfile changes.
- Reverted from custom testing image to
   ```YAML
   machine: True
   ```
   to get tests running.
</div>
<div class="keep-together" markdown="1">
Also
- cleaned up CSS to avoid lists breaking across columns and added

> Nested list items need exactly three spaces (`   `) of indentation in this flavor of Markdown.

to the README.
- Started [C-PAC testing spec]({{ site.baseurl }}/specs/c-pac-testing.html)
</div>