---
projects: [c-pac, bids-derivatives, c-pac-on-habanero]
author: [Jon Clucas]
date: 2020-07-16
---

- [ ] :construction: C-PAC v1.7.0
   - [x] C-PAC reg-test-1
   - [x] longitudinal
   - [ ] C-PAC {% octicon issue-opened height:12 class:"right left" aria-label:issue %} \#1260
- [x] BIDS derivatives meeting
- [ ] C-PAC on Habanero
<!--more--> 
### didn't get to

- [ ] C-PAC {% octicon issue-opened height:12 class:"right left" aria-label:issue %} \#1260
- [ ] C-PAC longitudinal testing
- [ ] C-PAC Python package v0.2.5
- [ ] simplify automated testing (C-PAC)
- [ ] spec Docker image for testing
- [ ] C-PAC ANTS priors testing
- [ ]
   ```Python
   requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/v1.35/containers/f613e7a80272cc015bc1e92a8c16a4c0e73bc3df98988c79a8a3c0df4f7be207/start
 docker.errors.APIError: 500 Server Error: Internal Server Error ("OCI runtime create failed: container_linux.go:348: starting container process caused 
 ```
   on Ned
- [ ] KnowB4 (:calendar: due September 30)

### C-PAC regtest-1
```Python
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/shutil.py", line 566, in move
    os.rename(src, real_dst)
FileNotFoundError: [Errno 2] No such file or directory: '/media/ebs/runs/2020-07-15_nightly_regtest-1/working/resting_preproc_sub-0025429_ses-2/anat_mni_ants_register_0/calc_ants_warp/_0x59f703005280b20d3f00133542a46f74_unfinished.json' -> '/media/ebs/runs/2020-07-15_nightly_regtest-1/working/resting_preproc_sub-0025429_ses-2/anat_mni_ants_register_0/calc_ants_warp/_0x59f703005280b20d3f00133542a46f74.json'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 69, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 480, in run
    hashfile_unfinished.replace('_unfinished', ''))
  File "/usr/local/miniconda/lib/python3.7/shutil.py", line 580, in move
    copy_function(src, real_dst)
  File "/usr/local/miniconda/lib/python3.7/shutil.py", line 266, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/local/miniconda/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/media/ebs/runs/2020-07-15_nightly_regtest-1/working/resting_preproc_sub-0025429_ses-2/anat_mni_ants_register_0/calc_ants_warp/_0x59f703005280b20d3f00133542a46f74_unfinished.json'
```

<table class="conversation"><tr><td>Hecheng</td><td markdown="1">
hm… json file…  did you check if the file exists there or not? I wonder if it doesn’t recognize the file or it actual doesn’t exist there
</td></tr><tr><td>Jon</td><td markdown="1">
It actually doesn't exist
```BASH
$ ls /media/ebs/runs/2020-07-15_nightly_regtest-1/working/resting_preproc_sub-0025429_ses-2/anat_mni_ants_register_0/calc_ants_warp
command.txt   _node.pklz  result_calc_ants_warp.pklz                     transform1Rigid.mat   transform3InverseWarp.nii.gz  transform_Warped.nii.gz
_inputs.pklz  _report     transform0DerivedInitialMovingTranslation.mat  transform2Affine.mat  transform3Warp.nii.gz
```
Since the filepath it's looking for has "unfinished" in the name, I wonder if it doesn't exist because it... finished?
</td></tr><tr><td>Xinhui</td><td markdown="1">
someone also reported this issue [FCP-INDI/C-PAC#1308](https://github.com/FCP-INDI/C-PAC/issues/1308)
</td></tr><tr><td>Hecheng</td><td markdown="1">
have you tried to delete the folder and restart as <img style="height:1em;" src="{{ site.baseurl }}/assets/images/絵文字/steve.png" alt=":steve:"> mentioned in the comment?
</td></tr><tr><td>Jon</td><td markdown="1">
doing that now
</td></tr></table>
```Python
Traceback (most recent call last):
  File "/code/run.py", line 606, in <module>
    test_config = 1 if args.analysis_level == "test_config" else 0
  File "/code/CPAC/pipeline/cpac_runner.py", line 519, in run
    p_name, plugin, plugin_args, test_config)
  File "/code/CPAC/pipeline/cpac_pipeline.py", line 319, in run_workflow
    subject_id, sub_dict, c, p_name, num_ants_cores
  File "/code/CPAC/pipeline/cpac_pipeline.py", line 1638, in build_workflow
    workflow, strat_list = connect_func_to_template_reg(workflow, strat_list, c)
  File "/code/CPAC/registration/registration.py", line 1231, in connect_func_to_template_reg
    func_type='non-ica-aroma')
  File "/code/CPAC/registration/output_func_to_standard.py", line 520, in output_func_to_standard
    num_ants_cores=pipeline_config_obj.num_ants_threads, registration_template=registration_template, func_type=func_type)
  File "/code/CPAC/registration/output_func_to_standard.py", line 396, in ants_apply_warps_func_mni
    node, out_file = strat[ants_transformation_dict[symmetry][transform_key]]
KeyError: 'blip_warp'
```

### BIDS derivatives
 
* meeting ― Steve, Azeez and I will meet to follow up

### C-PAC on Habanero

- get `FD1D` from Lisa, share with Steve

### C-PAC {% octicon issue-opened height:12 class:"right left" aria-label:issue %} \#1260

### C-PAC longitudinal

* 2020-07-16_feature-longitudinal_2549845_test-run.sh 

### C-PAC Python package

* clarify usage
* PR